---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
  - port: 7777
    nodePort: 7777
    protocol: UDP
    name: "game"
    targetPort: "game"
  - port: 7777
    nodePort: 7777
    protocol: TCP
    name: "gameTCP"
    targetPort: "gameTCP"
  selector:
    app: satisfactory
